-- Aufnahme 2026-10-05 22:02: als prologue.inputs ins Profil übernehmen
return {
  { wait = 292 },
  { keys = "A", frames = 21, release = 0 },
  { wait = 179 },
  { keys = "A", frames = 42, release = 0 },
  { wait = 635 },
  { keys = "A", frames = 61, release = 0 },
  { wait = 194 },
  { keys = "A", frames = 76, release = 0 },
  { wait = 257 },
  { keys = "A", frames = 58, release = 0 },
  { wait = 93 },
  { keys = "A", frames = 33, release = 0 },
  { wait = 134 },
  { keys = "A", frames = 22, release = 0 },
  { wait = 205 },
  { keys = "A", frames = 34, release = 0 },
  { wait = 303 },
  { keys = "A", frames = 33, release = 0 },
  { wait = 336 },
  { keys = "down", frames = 34, release = 0 },
  { wait = 148 },
  { keys = "A", frames = 53, release = 0 },
  { wait = 275 },
  { keys = "A", frames = 87, release = 0 },
  { wait = 516 },
  { keys = "A", frames = 35, release = 0 },
  { wait = 560 },
  { keys = "A", frames = 58, release = 0 },
  { wait = 76 },
  { keys = "A", frames = 28, release = 0 },
  { wait = 40 },
  { keys = "A", frames = 20, release = 0 },
  { wait = 46 },
  { keys = "A", frames = 27, release = 0 },
  { wait = 62 },
  { keys = "A", frames = 46, release = 0 },
  { wait = 68 },
  { keys = "A", frames = 33, release = 0 },
  { wait = 72 },
  { keys = "A", frames = 33, release = 0 },
  { wait = 81 },
  { keys = "A", frames = 39, release = 0 },
  { wait = 79 },
  { keys = "A", frames = 52, release = 0 },
  { wait = 60 },
  { keys = "A", frames = 31, release = 0 },
  { wait = 41 },
  { keys = "A", frames = 30, release = 0 },
  { wait = 108 },
  { keys = "A", frames = 37, release = 0 },
  { wait = 74 },
  { keys = "A", frames = 47, release = 0 },
  { wait = 69 },
  { keys = "A", frames = 29, release = 0 },
  { wait = 295 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 98 },
  { keys = "left", frames = 20, release = 0 },
  { wait = 30 },
  { keys = "A", frames = 50, release = 0 },
  { wait = 280 },
  { keys = "A", frames = 56, release = 0 },
  { wait = 191 },
  { keys = "A", frames = 30, release = 0 },
  { wait = 60 },
  { keys = "A", frames = 56, release = 0 },
  { wait = 124 },
  { keys = "A", frames = 29, release = 0 },
  { wait = 1991 },
  { keys = "A", frames = 40, release = 0 },
  { wait = 36 },
  { keys = "A", frames = 38, release = 0 },
  { wait = 46 },
  { keys = "A", frames = 40, release = 0 },
  { wait = 59 },
  { keys = "A", frames = 26, release = 0 },
  { wait = 54 },
  { keys = "A", frames = 32, release = 0 },
  { wait = 49 },
  { keys = "A", frames = 38, release = 0 },
  { wait = 56 },
  { keys = "A", frames = 48, release = 0 },
  { wait = 50 },
  { keys = "A", frames = 38, release = 0 },
  { wait = 62 },
  { keys = "A", frames = 35, release = 0 },
  { wait = 33 },
  { keys = "A", frames = 21, release = 0 },
  { wait = 290 },
  { keys = "start", frames = 63, release = 0 },
  { keys = "A+start", frames = 12, release = 0 },
  { keys = "A", frames = 79, release = 0 },
  { wait = 117 },
  { keys = "A", frames = 37, release = 0 },
  { wait = 74 },
  { keys = "A", frames = 21, release = 0 },
  { wait = 48 },
  { keys = "A", frames = 24, release = 0 },
  { wait = 54 },
  { keys = "A", frames = 40, release = 0 },
  { wait = 57 },
  { keys = "A", frames = 35, release = 0 },
  { wait = 61 },
  { keys = "A", frames = 29, release = 0 },
  { wait = 63 },
  { keys = "A", frames = 22, release = 0 },
  { wait = 63 },
  { keys = "A", frames = 24, release = 0 },
  { wait = 63 },
  { keys = "A", frames = 28, release = 0 },
  { wait = 62 },
  { keys = "A", frames = 36, release = 0 },
  { wait = 64 },
  { keys = "A", frames = 19, release = 0 },
  { wait = 44 },
  { keys = "A", frames = 20, release = 0 },
  { wait = 41 },
  { keys = "A", frames = 19, release = 0 },
  { wait = 64 },
  { keys = "A", frames = 38, release = 0 },
  { wait = 66 },
  { keys = "A", frames = 35, release = 0 },
  { wait = 62 },
  { keys = "A", frames = 56, release = 0 },
  { wait = 73 },
  { keys = "A", frames = 56, release = 0 },
  { wait = 52 },
  { keys = "A", frames = 33, release = 0 },
  { wait = 58 },
  { keys = "A", frames = 52, release = 0 },
  { wait = 380 },
  { keys = "A", frames = 74, release = 0 },
  { wait = 73 },
  { keys = "A", frames = 47, release = 0 },
  { wait = 75 },
  { keys = "A", frames = 45, release = 0 },
  { wait = 54 },
  { keys = "A", frames = 26, release = 0 },
  { wait = 24 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 7, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 17, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 19 },
  { keys = "A", frames = 9, release = 0 },
  { keys = "A+right", frames = 9, release = 0 },
  { keys = "right", frames = 22, release = 0 },
  { keys = "A+right", frames = 20, release = 0 },
  { keys = "right", frames = 17, release = 0 },
  { keys = "A+right", frames = 18, release = 0 },
  { keys = "right", frames = 17, release = 0 },
  { keys = "up+right", frames = 9, release = 0 },
  { keys = "up", frames = 22, release = 0 },
  { wait = 4 },
  { keys = "right", frames = 4, release = 0 },
  { keys = "A+right", frames = 14, release = 0 },
  { keys = "right", frames = 14, release = 0 },
  { wait = 6 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 17, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 19, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 32 },
  { keys = "A", frames = 19, release = 0 },
  { wait = 20 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 100 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 17 },
  { keys = "right", frames = 78, release = 0 },
  { keys = "up+right", frames = 3, release = 0 },
  { keys = "right", frames = 29, release = 0 },
  { wait = 13 },
  { keys = "right", frames = 12, release = 0 },
  { keys = "up+right", frames = 6, release = 0 },
  { keys = "up", frames = 51, release = 0 },
  { keys = "up+right", frames = 5, release = 0 },
  { keys = "right", frames = 96, release = 0 },
  { wait = 63 },
  { keys = "down", frames = 58, release = 0 },
  { keys = "A+down", frames = 13, release = 0 },
  { keys = "down", frames = 16, release = 0 },
  { keys = "A+down", frames = 9, release = 0 },
  { keys = "A", frames = 5, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 88 },
  { keys = "down", frames = 122, release = 0 },
  { keys = "down+left", frames = 5, release = 0 },
  { keys = "left", frames = 66, release = 0 },
  { keys = "down+left", frames = 4, release = 0 },
  { keys = "down", frames = 40, release = 0 },
  { keys = "down+right", frames = 8, release = 0 },
  { keys = "right", frames = 8, release = 0 },
  { wait = 15 },
  { keys = "down", frames = 92, release = 0 },
  { keys = "A+down", frames = 16, release = 0 },
  { keys = "down", frames = 13, release = 0 },
  { keys = "A+down", frames = 3, release = 0 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 9 },
  { keys = "down", frames = 9, release = 0 },
  { keys = "A+down", frames = 14, release = 0 },
  { keys = "down", frames = 5, release = 0 },
  { wait = 8 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 6, release = 0 },
  { keys = "A+down", frames = 1, release = 0 },
  { keys = "down", frames = 63, release = 0 },
  { wait = 115 },
  { keys = "left", frames = 79, release = 0 },
  { keys = "up+left", frames = 5, release = 0 },
  { keys = "up", frames = 97, release = 0 },
  { keys = "up+left", frames = 9, release = 0 },
  { keys = "left", frames = 85, release = 0 },
  { keys = "up+left", frames = 7, release = 0 },
  { keys = "up", frames = 142, release = 0 },
  { keys = "A+up", frames = 2, release = 0 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 7 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 7 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "up", frames = 18, release = 0 },
  { keys = "A+up", frames = 10, release = 0 },
  { keys = "up", frames = 21, release = 0 },
  { keys = "A+up", frames = 12, release = 0 },
  { keys = "up", frames = 13, release = 0 },
  { wait = 8 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 15 },
  { keys = "up", frames = 1, release = 0 },
  { keys = "A+up", frames = 13, release = 0 },
  { keys = "up", frames = 16, release = 0 },
  { keys = "A+up", frames = 11, release = 0 },
  { keys = "up", frames = 15, release = 0 },
  { keys = "A+up", frames = 10, release = 0 },
  { keys = "up", frames = 13, release = 0 },
  { keys = "A+up", frames = 9, release = 0 },
  { keys = "up", frames = 12, release = 0 },
  { keys = "A+up", frames = 10, release = 0 },
  { keys = "up", frames = 10, release = 0 },
  { keys = "A+up", frames = 9, release = 0 },
  { keys = "up", frames = 12, release = 0 },
  { keys = "A+up", frames = 8, release = 0 },
  { keys = "up", frames = 32, release = 0 },
  { keys = "A+up", frames = 8, release = 0 },
  { keys = "up", frames = 262, release = 0 },
  { keys = "up+left", frames = 7, release = 0 },
  { keys = "left", frames = 74, release = 0 },
  { keys = "up+left", frames = 6, release = 0 },
  { keys = "up", frames = 55, release = 0 },
  { keys = "up+right", frames = 24, release = 0 },
  { keys = "right", frames = 98, release = 0 },
  { wait = 67 },
  { keys = "down", frames = 31, release = 0 },
  { keys = "A+down", frames = 3, release = 0 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 68 },
  { keys = "up", frames = 46, release = 0 },
  { keys = "up+left", frames = 7, release = 0 },
  { keys = "up", frames = 36, release = 0 },
  { keys = "up+left", frames = 9, release = 0 },
  { keys = "left", frames = 81, release = 0 },
  { wait = 84 },
  { keys = "down", frames = 85, release = 0 },
  { keys = "down+right", frames = 8, release = 0 },
  { keys = "right", frames = 58, release = 0 },
  { keys = "down+right", frames = 9, release = 0 },
  { keys = "down", frames = 74, release = 0 },
  { wait = 92 },
  { keys = "right", frames = 107, release = 0 },
  { keys = "up+right", frames = 56, release = 0 },
  { keys = "up", frames = 91, release = 0 },
  { keys = "A+up", frames = 9, release = 0 },
  { keys = "up", frames = 78, release = 0 },
  { keys = "up+right", frames = 11, release = 0 },
  { keys = "up", frames = 114, release = 0 },
  { keys = "A+up", frames = 11, release = 0 },
  { keys = "A", frames = 1, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 7, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 5, release = 0 },
  { wait = 23 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 41 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 21 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 24 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 24 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 7 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 21 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 71 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 17, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 8, release = 0 },
  { wait = 8 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 9, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 17, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 9 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 22 },
  { keys = "left", frames = 32, release = 0 },
  { keys = "A+left", frames = 11, release = 0 },
  { keys = "left", frames = 11, release = 0 },
  { keys = "A+left", frames = 10, release = 0 },
  { keys = "left", frames = 4, release = 0 },
  { wait = 7 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 20 },
  { keys = "left", frames = 5, release = 0 },
  { keys = "A+left", frames = 10, release = 0 },
  { keys = "left", frames = 14, release = 0 },
  { keys = "A+left", frames = 12, release = 0 },
  { keys = "left", frames = 14, release = 0 },
  { keys = "A+left", frames = 10, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 13, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 5, release = 0 },
  { keys = "A+left", frames = 8, release = 0 },
  { keys = "left", frames = 12, release = 0 },
  { keys = "A+left", frames = 10, release = 0 },
  { keys = "left", frames = 12, release = 0 },
  { keys = "A+left", frames = 10, release = 0 },
  { keys = "left", frames = 13, release = 0 },
  { keys = "A+left", frames = 12, release = 0 },
  { keys = "left", frames = 14, release = 0 },
  { keys = "A+left", frames = 11, release = 0 },
  { keys = "left", frames = 13, release = 0 },
  { keys = "A+left", frames = 9, release = 0 },
  { keys = "left", frames = 19, release = 0 },
  { keys = "A+left", frames = 8, release = 0 },
  { keys = "left", frames = 29, release = 0 },
  { keys = "A+left", frames = 11, release = 0 },
  { keys = "left", frames = 12, release = 0 },
  { keys = "A+left", frames = 11, release = 0 },
  { keys = "left", frames = 19, release = 0 },
  { keys = "A+left", frames = 7, release = 0 },
  { keys = "left", frames = 17, release = 0 },
  { keys = "A+left", frames = 9, release = 0 },
  { keys = "left", frames = 15, release = 0 },
  { keys = "A+left", frames = 11, release = 0 },
  { keys = "left", frames = 14, release = 0 },
  { keys = "A+left", frames = 13, release = 0 },
  { keys = "left", frames = 76, release = 0 },
  { wait = 10 },
  { keys = "left", frames = 9, release = 0 },
  { wait = 1 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 95 },
}
