-- Aufnahme 2026-10-05 22:31: als prologue.inputs ins Profil übernehmen
return {
  { wait = 26 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 108 },
  { keys = "A", frames = 85, release = 0 },
  { wait = 97 },
  { keys = "A", frames = 88, release = 0 },
  { wait = 200 },
  { keys = "A", frames = 53, release = 0 },
  { wait = 73 },
  { keys = "A", frames = 69, release = 0 },
  { wait = 72 },
  { keys = "A", frames = 51, release = 0 },
  { wait = 96 },
  { keys = "A", frames = 40, release = 0 },
  { wait = 59 },
  { keys = "A", frames = 32, release = 0 },
  { wait = 56 },
  { keys = "A", frames = 42, release = 0 },
  { wait = 53 },
  { keys = "A", frames = 24, release = 0 },
  { wait = 91 },
  { keys = "A", frames = 36, release = 0 },
  { wait = 73 },
  { keys = "A", frames = 67, release = 0 },
  { wait = 583 },
  { keys = "down", frames = 47, release = 0 },
  { wait = 80 },
  { keys = "A", frames = 97, release = 0 },
  { wait = 72 },
  { keys = "A", frames = 60, release = 0 },
  { wait = 67 },
  { keys = "A", frames = 57, release = 0 },
  { wait = 223 },
  { touch = { x = 132, y = 82 }, frames = 2, release = 0 },
  { touch = { x = 132, y = 84 }, frames = 4, release = 0 },
  { touch = { x = 132, y = 85 }, frames = 3, release = 0 },
  { touch = { x = 132, y = 86 }, frames = 1, release = 0 },
  { touch = { x = 132, y = 88 }, frames = 5, release = 0 },
  { touch = { x = 132, y = 89 }, frames = 29, release = 0 },
  { wait = 93 },
  { touch = { x = 131, y = 88 }, frames = 52, release = 0 },
  { wait = 42 },
  { keys = "A", frames = 48, release = 0 },
  { wait = 74 },
  { touch = { x = 130, y = 89 }, frames = 42, release = 0 },
  { wait = 90 },
  { touch = { x = 130, y = 89 }, frames = 24, release = 0 },
  { wait = 89 },
  { keys = "A", frames = 50, release = 0 },
  { wait = 51 },
  { keys = "A", frames = 26, release = 0 },
  { wait = 35 },
  { keys = "A", frames = 24, release = 0 },
  { wait = 39 },
  { keys = "A", frames = 32, release = 0 },
  { wait = 54 },
  { keys = "A", frames = 53, release = 0 },
  { wait = 56 },
  { keys = "A", frames = 33, release = 0 },
  { wait = 59 },
  { keys = "A", frames = 37, release = 0 },
  { wait = 58 },
  { keys = "A", frames = 36, release = 0 },
  { wait = 57 },
  { keys = "A", frames = 49, release = 0 },
  { wait = 58 },
  { keys = "A", frames = 51, release = 0 },
  { wait = 44 },
  { keys = "A", frames = 20, release = 0 },
  { wait = 46 },
  { keys = "A", frames = 25, release = 0 },
  { wait = 52 },
  { keys = "A", frames = 69, release = 0 },
  { wait = 72 },
  { keys = "A", frames = 46, release = 0 },
  { wait = 258 },
  { keys = "left", frames = 35, release = 0 },
  { keys = "A+left", frames = 18, release = 0 },
  { keys = "A", frames = 49, release = 0 },
  { wait = 53 },
  { keys = "A", frames = 26, release = 0 },
  { wait = 56 },
  { keys = "left", frames = 27, release = 0 },
  { wait = 19 },
  { keys = "A", frames = 62, release = 0 },
  { wait = 136 },
  { keys = "A", frames = 58, release = 0 },
  { wait = 281 },
  { keys = "A", frames = 46, release = 0 },
  { wait = 51 },
  { keys = "A", frames = 45, release = 0 },
  { wait = 56 },
  { keys = "A", frames = 28, release = 0 },
  { wait = 464 },
  { touch = { x = 174, y = 117 }, frames = 30, release = 0 },
  { wait = 202 },
  { touch = { x = 66, y = 69 }, frames = 16, release = 0 },
  { wait = 398 },
  { touch = { x = 97, y = 120 }, frames = 15, release = 0 },
  { wait = 222 },
  { touch = { x = 67, y = 119 }, frames = 18, release = 0 },
  { wait = 148 },
  { touch = { x = 218, y = 69 }, frames = 31, release = 0 },
  { wait = 41 },
  { keys = "A", frames = 42, release = 0 },
  { wait = 83 },
  { keys = "A", frames = 63, release = 0 },
  { wait = 65 },
  { keys = "A", frames = 44, release = 0 },
  { wait = 73 },
  { keys = "A", frames = 52, release = 0 },
  { wait = 62 },
  { keys = "A", frames = 31, release = 0 },
  { wait = 43 },
  { keys = "A", frames = 24, release = 0 },
  { wait = 37 },
  { keys = "A", frames = 28, release = 0 },
  { wait = 34 },
  { keys = "A", frames = 57, release = 0 },
  { wait = 55 },
  { keys = "A", frames = 45, release = 0 },
  { wait = 55 },
  { keys = "A", frames = 36, release = 0 },
  { wait = 410 },
  { keys = "up", frames = 42, release = 0 },
  { wait = 79 },
  { keys = "down", frames = 51, release = 0 },
  { wait = 47 },
  { keys = "A", frames = 65, release = 0 },
  { wait = 136 },
  { keys = "A", frames = 66, release = 0 },
  { wait = 46 },
  { keys = "A", frames = 67, release = 0 },
  { wait = 54 },
  { keys = "A", frames = 56, release = 0 },
  { wait = 34 },
  { keys = "A", frames = 44, release = 0 },
  { wait = 29 },
  { keys = "A", frames = 30, release = 0 },
  { wait = 41 },
  { keys = "A", frames = 36, release = 0 },
  { wait = 45 },
  { keys = "A", frames = 36, release = 0 },
  { wait = 50 },
  { keys = "A", frames = 40, release = 0 },
  { wait = 56 },
  { keys = "A", frames = 32, release = 0 },
  { wait = 48 },
  { keys = "A", frames = 40, release = 0 },
  { wait = 47 },
  { keys = "A", frames = 42, release = 0 },
  { wait = 53 },
  { keys = "A", frames = 34, release = 0 },
  { wait = 38 },
  { keys = "A", frames = 25, release = 0 },
  { wait = 33 },
  { keys = "A", frames = 32, release = 0 },
  { wait = 37 },
  { keys = "A", frames = 32, release = 0 },
  { wait = 55 },
  { keys = "A", frames = 49, release = 0 },
  { wait = 62 },
  { keys = "A", frames = 56, release = 0 },
  { wait = 96 },
  { keys = "A", frames = 40, release = 0 },
  { wait = 79 },
  { keys = "A", frames = 48, release = 0 },
  { wait = 237 },
  { keys = "A", frames = 65, release = 0 },
  { wait = 100 },
  { keys = "A", frames = 59, release = 0 },
  { wait = 92 },
  { keys = "A", frames = 69, release = 0 },
  { wait = 110 },
  { keys = "A", frames = 48, release = 0 },
  { wait = 19 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 36 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 28 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 12, release = 0 },
  { wait = 11 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 15 },
  { keys = "A", frames = 11, release = 0 },
  { wait = 12 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 13 },
  { keys = "A", frames = 10, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 14 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 16 },
  { keys = "A", frames = 18, release = 0 },
  { wait = 18 },
  { keys = "A", frames = 15, release = 0 },
  { wait = 17 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 28 },
  { keys = "A", frames = 22, release = 0 },
  { wait = 21 },
  { keys = "A", frames = 18, release = 0 },
  { wait = 134 },
  { keys = "right", frames = 7, release = 0 },
  { wait = 12 },
  { keys = "right", frames = 23, release = 0 },
  { keys = "up", frames = 14, release = 0 },
  { wait = 109 },
  { keys = "A", frames = 40, release = 0 },
  { wait = 10 },
  { keys = "A", frames = 14, release = 0 },
  { wait = 7 },
  { keys = "A", frames = 16, release = 0 },
  { wait = 29 },
}
