-- Solo-Modus: lokaler Vermittler mit derselben Regel-Engine.
local T = require("lib.t")
local json = require("lib.json")
local FS = require("net.fs")
local Hub = require("net.local_hub")
local Client = require("net.client")

local function setup(mem, opts)
  mem = mem or FS.memory()
  local clock = { t = 5000 }
  local hub = Hub.new({ fs = mem, dir = "local", name = "Tom", now = function() return clock.t end,
    settings = opts and opts.settings, auto_start = not (opts and opts.no_start) })
  local c = Client.new({ transport = hub, name = "Tom", lobby = "SOLO", now = function() return clock.t end,
    fs = mem, queue_path = "local/q.json", stats_path = "local/todeszaehler.json" })
  return c, hub, mem, clock
end

T.test("Solo: Anmeldung ohne Server, Run startet automatisch mit Vorlage", function()
  local c, hub = setup(nil, { settings = { preset = "hardcore" } })
  c:poll()
  T.ok(c:online())
  T.eq(c.player, "tom")
  T.eq(c.state.phase, "running")
  T.eq(c.state.settings.preset, "hardcore")
  T.eq(#c.state.teams.t1.members, 1)
  T.eq(c:status_text(), "Solo (ohne Server)")
  T.eq(hub.stats.tom.attempts, 1)
end)

T.test("Solo: Regeln greifen – Fang bildet Gruppe der Größe 1, Tod zählt, Run verloren", function()
  local c = setup()
  c:poll()
  c:send_event({ type = "status", has_balls = true })
  c:send_event({ type = "catch", uid = "m1", species_name = "Plinfa", area = { key = "1", name = "Zweiblattdorf" } })
  c:poll()
  T.eq(c.state.teams.t1.groups.g1.status, "komplett")
  c:send_event({ type = "faint", uid = "m1", opponent = "Rivale" })
  c:poll()
  T.eq(c.state.players.tom.mons.m1.status, "tot")
  T.eq(c.state.phase, "finished")
  T.eq(c.stats.tom.deaths, 1)
  T.eq(#c.queue, 0, "alles bestätigt")
  local fx = c:take_effects()
  local kill = false
  for _, e in ipairs(fx) do if e.type == "kill" then kill = true end end
  T.ok(kill)
end)

T.test("Solo: Zustand und Todeszähler überstehen einen Neustart", function()
  local c, _, mem, clock = setup()
  c:poll()
  c:send_event({ type = "status", has_balls = true })
  c:send_event({ type = "catch", uid = "m1", area = { key = "1", name = "A" } })
  c:send_event({ type = "catch", uid = "m2", area = { key = "2", name = "B" } })
  c:send_event({ type = "faint", uid = "m1" })
  c:poll()
  T.ok(mem.files["local/solo_tom.json"])
  local c2 = setup(mem)
  T.eq(c2.stats.tom.deaths, 1, "lokale Kopie schon vor der Anmeldung")
  c2:poll()
  T.eq(c2.state.phase, "running")
  T.eq(c2.state.players.tom.mons.m1.status, "tot")
  T.eq(c2.state.players.tom.mons.m2.status, "lebt")
  T.eq(c2.state.attempt, 1, "kein zweiter Auto-Start")
  T.eq(c2:send_event({ type = "status", badges = 1 }), 5, "Sequenz läuft weiter")
  c2:poll()
  T.eq(c2.state.players.tom.badges, 1)
end)

T.test("Solo: neuer Versuch nach Run-Ende, Fehler werden gemeldet", function()
  local c = setup()
  c:poll()
  c:send_event({ type = "new_attempt" })
  c:poll()
  T.ok(c.errors[1]:find("erst nach Run%-Ende"))
  c:send_event({ type = "status", has_balls = true })
  c:send_event({ type = "catch", uid = "m1", area = { key = "1", name = "A" } })
  c:send_event({ type = "faint", uid = "m1" })
  c:send_event({ type = "new_attempt" })
  c:send_event({ type = "start_run" })
  c:poll()
  T.eq(c.state.attempt, 2)
  T.eq(c.state.phase, "running")
end)
