-- Aufhol-Modus: ein Mitspieler der eigenen Gruppe ist offline.
local T = require("lib.t")
local H = require("core.helpers")
local R = require("core.rules")

T.test("Aufhol-Modus aktiv, sobald ein Partner offline ist", function()
  local s = H.run(2)
  T.no((R.catchup_active(s.state, "anna")))
  local eff = s:ok("offline", "ben")
  T.has(eff, { type = "notify", level = "warn" })
  local active, off = R.catchup_active(s.state, "anna")
  T.ok(active)
  T.eq(off, { "ben" })
  s:ok("online", "ben")
  T.no((R.catchup_active(s.state, "anna")))
end)

T.test("Solo-Spieler hat nie Aufhol-Modus", function()
  local s = H.run(1)
  T.no((R.catchup_active(s.state, "anna")))
  T.ok(R.catch_allowed(s.state, "anna", "201"))
end)

T.test("Fortschritt nur bis zum Ordenstand des Partners", function()
  local s = H.run(2)
  s:ok("status", "ben", { badges = 2 })
  s:ok("status", "anna", { badges = 1 })
  s:ok("offline", "ben")
  T.ok(R.gym_allowed(s.state, "anna"), "hinter dem Partner: erlaubt")
  s:ok("status", "anna", { badges = 2 })
  local ok, reason = R.gym_allowed(s.state, "anna")
  T.no(ok, "gleich weit: gesperrt")
  T.ok(reason:find("Aufhol"))
  -- Orden trotzdem geholt: Verstoß wird protokolliert
  local eff = s:ok("status", "anna", { badges = 3 })
  T.has(eff, { type = "notify", level = "alarm" })
  T.eq(s:p("anna").violations, 1)
  -- Partner wieder da: frei
  s:ok("online", "ben")
  T.ok(R.gym_allowed(s.state, "anna"))
end)

T.test("Fänge nur in Gebieten, in denen der Partner schon gefangen hat", function()
  local s = H.run(2)
  s:ok("catch", "ben", { uid = "ben-a", area = H.AREA1 })
  s:ok("offline", "ben")
  T.ok(R.catch_allowed(s.state, "anna", "201"))
  local ok, _, kind = R.catch_allowed(s.state, "anna", "202")
  T.no(ok)
  T.eq(kind, "aufhol")
  -- Fang im Partner-Gebiet: Gruppe sofort komplett
  local eff = s:ok("catch", "anna", { uid = "anna-a", area = H.AREA1 })
  T.eq(s:team("anna").groups.g1.status, "komplett")
  T.has(eff, { type = "discord", kind = "group" })
  -- Fang in fremdem Gebiet: gesperrt (tot), Gebiet bleibt für beide offen
  s:ok("catch", "anna", { uid = "anna-x", area = H.AREA2 })
  T.eq(s:mon("anna", "anna-x").status, "tot")
  T.eq(s:mon("anna", "anna-x").cause, "gesperrt")
  T.eq(s:team("anna").areas["202"].by.anna, nil)
  T.no(s:team("anna").areas["202"].consumed)
  -- Partner zurück: Gebiet 202 ist normal nutzbar
  s:ok("online", "ben")
  T.ok(R.catch_allowed(s.state, "anna", "202"))
end)

T.test("Begegnung ohne Fang in fremdem Gebiet verbraucht nichts", function()
  local s = H.run(2)
  s:ok("offline", "ben")
  s:ok("encounter_failed", "anna", { area = H.AREA2 })
  T.no(s:team("anna").areas["202"].consumed)
end)

T.test("Verpasster Fang im Partner-Gebiet verbraucht es und tötet das Partner-Monster", function()
  local s = H.run(2)
  s:ok("catch", "ben", { uid = "ben-a", area = H.AREA1 })
  s:ok("offline", "ben")
  local eff = s:ok("encounter_failed", "anna", { area = H.AREA1 })
  T.ok(s:team("anna").areas["201"].consumed)
  T.has(eff, { type = "kill", player = "ben", uid = "ben-a" })
  T.eq(#s:p("ben").absence, 1)
end)

T.test("Tode werden beim Partner nach dem Wiederverbinden angewendet und gelistet", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("offline", "ben")
  s:ok("faint", "anna", { uid = "anna-a", opponent = "Wildes Monster" })
  s:ok("faint", "anna", { uid = "anna-b" })
  T.eq(s:mon("ben", "ben-a").status, "tot")
  T.eq(s:mon("ben", "ben-b").status, "tot")
  T.eq(#s:p("ben").absence, 2)
  T.eq(s:p("ben").dragged, 2)
  -- Run ist mit allen Gruppen tot verloren – auch das sieht ben beim Wiederverbinden
  T.eq(s.state.phase, "finished")
  local eff = s:ok("online", "ben")
  local rep = T.has(eff, { type = "absence_report", player = "ben" })
  T.eq(#rep.deaths, 2)
  T.eq(rep.deaths[1].uid, "ben-a")
  T.eq(rep.deaths[1].by, "Arta (Anna)")
  T.eq(R.dead_uids(s.state, "ben"), { "ben-a", "ben-b" })
  s:ok("ack_absence", "ben")
  T.eq(#s:p("ben").absence, 0)
end)

T.test("Liste bleibt bis zur Bestätigung erhalten, auch über mehrere Verbindungen", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("offline", "ben")
  s:ok("faint", "anna", { uid = "anna-a" })
  s:ok("online", "ben")
  s:ok("offline", "ben")
  local eff = s:ok("online", "ben")
  T.has(eff, { type = "absence_report", player = "ben" })
end)

T.test("Team-Gleichheit vergleicht nur mit Mitspielern, die online sind", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("party", "anna", { mons = { "anna-a" } })
  s:ok("party", "ben", { mons = { "ben-a", "ben-b" } })
  T.no(R.team_check(s.state, "anna").ok)
  s:ok("offline", "ben")
  T.ok(R.team_check(s.state, "anna").ok)
end)

T.test("3 Spieler, einer offline: Sperren gelten nur bezüglich des Abwesenden", function()
  local s = H.run(3)
  s:ok("catch", "cem", { uid = "cem-a", area = H.AREA1 })
  s:ok("offline", "cem")
  T.ok(R.catch_allowed(s.state, "anna", "201"))
  T.ok(R.catch_allowed(s.state, "ben", "201"))
  T.no((R.catch_allowed(s.state, "anna", "202")))
  s:ok("catch", "anna", { uid = "anna-a", area = H.AREA1 })
  T.eq(s:team("anna").groups.g1.status, "offen", "ben fehlt noch")
  s:ok("catch", "ben", { uid = "ben-a", area = H.AREA1 })
  T.eq(s:team("anna").groups.g1.status, "komplett")
  -- Tod während cem offline: nur cem bekommt die Abwesenheitsliste
  s:ok("faint", "ben", { uid = "ben-a" })
  T.eq(#s:p("cem").absence, 1)
  T.eq(#s:p("anna").absence, 0)
end)

T.test("4 Spieler, zwei offline: Fang nur, wo beide schon gefangen haben", function()
  local s = H.run(4)
  s:ok("catch", "cem", { uid = "cem-a", area = H.AREA1 })
  s:ok("catch", "dana", { uid = "dana-a", area = H.AREA1 })
  s:ok("catch", "cem", { uid = "cem-b", area = H.AREA2 })
  s:ok("offline", "cem")
  s:ok("offline", "dana")
  T.ok(R.catch_allowed(s.state, "anna", "201"))
  T.no((R.catch_allowed(s.state, "anna", "202")), "dana hat in 202 noch nicht gefangen")
  s:ok("status", "cem", { badges = 3 })
  s:ok("status", "dana", { badges = 1 })
  s:ok("status", "anna", { badges = 1 })
  T.no((R.gym_allowed(s.state, "anna")), "Minimum der Abwesenden zählt")
end)

T.test("Wettkampf 2v2: Aufhol-Modus und Tode bleiben im eigenen Team", function()
  local s = H.run(4, { teams = { { "anna", "ben" }, { "cem", "dana" } } })
  T.eq(s:p("anna").team, "t1")
  T.eq(s:p("cem").team, "t2")
  s:ok("offline", "cem")
  T.no((R.catchup_active(s.state, "anna")), "Gegner offline ist kein Aufhol-Modus")
  T.ok((R.catchup_active(s.state, "dana")))
  H.catch_all(s, H.AREA1, "a")
  T.eq(s:team("anna").groups.g1.status, "komplett")
  T.eq(s:team("cem").groups.g2.status, "komplett")
  local eff = s:ok("faint", "anna", { uid = "anna-a" })
  T.eq(H.count(eff, { type = "kill" }), 2)
  T.eq(s:mon("cem", "cem-a").status, "lebt")
  T.eq(s:mon("dana", "dana-a").status, "lebt")
  -- Team 1 scheidet aus, Team 2 spielt weiter
  T.eq(s:team("anna").status, "verloren")
  T.eq(s.state.phase, "running")
  local rank = R.ranking(s.state)
  T.eq(rank[1].team, "t2")
  T.eq(rank[2].team, "t1")
end)

T.test("Wettkampf 1v1: Solo-Teams sind Gruppen der Größe 1", function()
  local s = H.run(2, { teams = { { "anna" }, { "ben" } }, settings = { goal = { kind = "orden", value = 1 } } })
  s:ok("catch", "anna", { uid = "anna-a", area = H.AREA1 })
  T.eq(s:team("anna").groups.g1.status, "komplett")
  s:ok("catch", "ben", { uid = "ben-a", area = H.AREA1 })
  T.eq(s:team("ben").groups.g2.status, "komplett")
  s:ok("status", "ben", { badges = 1 })
  T.eq(s:team("ben").status, "fertig")
  T.eq(s:team("ben").place, 1)
  T.eq(s.state.phase, "running")
  s:ok("status", "anna", { badges = 1 })
  T.eq(s:team("anna").place, 2)
  T.eq(s.state.phase, "finished")
  T.eq(s.state.result, "gewonnen")
  local rank = R.ranking(s.state)
  T.eq(rank[1].team, "t2")
end)
