local T = require("lib.t")
local H = require("core.helpers")
local X = require("core.export")

T.test("Todesprotokoll: Kopf mit Zählern, neueste Tode zuerst, Ursache", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("faint", "anna", { uid = "anna-a", level = 12, opponent = "Rivale" })
  local text = X.deathlog(s.state, { anna = { deaths = 4, dragged = 1, attempts = 3 } })
  local lines = {}
  for l in text:gmatch("[^\n]+") do lines[#lines + 1] = l end
  T.ok(lines[1]:find("Versuch 1"))
  T.ok(lines[2]:find("Anna: 4 Tode, 1 mitgerissen, 3 Versuche"), lines[2])
  T.ok(lines[2]:find("Ben: 0 Tode"), lines[2])
  T.eq(#lines, 4)
  T.ok(text:find("Arta %(Anna%) Lv%.12 in Route 201 gegen Rivale – gefallen"), text)
  T.ok(text:find("%(Ben%) Lv%.5 in Route 201 gegen Rivale – mitgerissen"), text)
end)

T.test("Todesprotokoll: leer und abgeschaltet", function()
  local s = H.run(1)
  T.ok(X.deathlog(s.state):find("Noch keine Tode"))
  local s2 = H.run(1, { settings = { death_log = false } })
  T.ok(X.deathlog(s2.state):find("abgeschaltet"))
end)

T.test("Zeitstempel mit Datum (UTC), auch Schaltjahr", function()
  T.eq(X.clock(1759700000000), "05.10. 21:33 UTC")
  local y, m, d = X.civil(math.floor(951782400 / 86400)) -- 29.02.2000
  T.eq({ y, m, d }, { 2000, 2, 29 })
  T.eq(X.clock(0), "--.--. --:--")
end)

T.test("Todesprotokoll über alle Versuche bleibt nach neuem Versuch erhalten", function()
  local L = require("core.ledger")
  local ledger = L.new()
  local s = H.run(1)
  local function feed(eff)
    L.apply(ledger, eff, { anna = "Anna" })
  end
  feed(s:ok("catch", "anna", { uid = "a1", species_name = "Plinfa", area = H.AREA1 }))
  feed(s:ok("faint", "anna", { uid = "a1", level = 6, opponent = "Rivale" }))
  T.eq(s.state.phase, "finished")
  feed(s:ok("new_attempt", "anna"))
  feed(s:ok("start_run", "anna"))
  feed(s:ok("status", "anna", { has_balls = true }))
  feed(s:ok("catch", "anna", { uid = "b1", species_name = "Chelast", area = H.AREA2 }))
  feed(s:ok("faint", "anna", { uid = "b1", level = 9 }))
  T.eq(#ledger.deathlog, 2)
  T.eq(ledger.deathlog[1].attempt, 1)
  T.eq(ledger.deathlog[2].attempt, 2)
  local text = X.deathlog_all(L.view(ledger, { "anna" }))
  local first = text:find("Versuch 2  Chelast")
  local second = text:find("Versuch 1  Plinfa")
  T.ok(first and second and first < second, text)
  T.ok(text:find("Plinfa %(Anna%) Lv%.6 in Route 201 gegen Rivale – gefallen"), text)
end)

T.test("Todesprotokoll abgeschaltet: keine dauerhaften Einträge", function()
  local s = H.run(1, { settings = { death_log = false } })
  s:ok("catch", "anna", { uid = "a1", area = H.AREA1 })
  local eff = s:ok("faint", "anna", { uid = "a1" })
  T.no(T.find(eff, { type = "death" }))
  T.eq(#s:team("anna").graveyard, 1, "Friedhof bleibt (für die Regeln)")
end)
