local T = require("lib.t")
local H = require("core.helpers")
local X = require("core.export")

T.test("Todesprotokoll: Kopf mit Zählern, neueste Tode zuerst, Ursache", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("faint", "anna", { uid = "anna-a", level = 12, opponent = "Rivale" })
  local text = X.deathlog(s.state, { anna = { deaths = 4, dragged = 1, attempts = 3 } })
  local lines = {}
  for l in text:gmatch("[^\n]+") do lines[#lines + 1] = l end
  T.ok(lines[1]:find("Versuch 1"))
  T.ok(lines[2]:find("Anna: 4 Tode, 1 mitgerissen, 3 Versuche"), lines[2])
  T.ok(lines[2]:find("Ben: 0 Tode"), lines[2])
  T.eq(#lines, 4)
  T.ok(text:find("Arta %(Anna%) Lv%.12 in Route 201 gegen Rivale – gefallen"), text)
  T.ok(text:find("%(Ben%) Lv%.5 in Route 201 gegen Rivale – mitgerissen"), text)
end)

T.test("Todesprotokoll: leer und abgeschaltet", function()
  local s = H.run(1)
  T.ok(X.deathlog(s.state):find("Noch keine Tode"))
  local s2 = H.run(1, { settings = { death_log = false } })
  T.ok(X.deathlog(s2.state):find("abgeschaltet"))
end)

T.test("Zeitstempel mit Datum (UTC), auch Schaltjahr", function()
  T.eq(X.clock(1759700000000), "05.10. 21:33 UTC")
  local y, m, d = X.civil(math.floor(951782400 / 86400)) -- 29.02.2000
  T.eq({ y, m, d }, { 2000, 2, 29 })
  T.eq(X.clock(0), "--.--. --:--")
end)

T.test("Todesprotokoll über alle Versuche bleibt nach neuem Versuch erhalten", function()
  local L = require("core.ledger")
  local ledger = L.new()
  local s = H.run(1)
  local function feed(eff)
    L.apply(ledger, eff, { anna = "Anna" })
  end
  feed(s:ok("catch", "anna", { uid = "a1", species_name = "Plinfa", area = H.AREA1 }))
  feed(s:ok("faint", "anna", { uid = "a1", level = 6, opponent = "Rivale" }))
  T.eq(s.state.phase, "finished")
  feed(s:ok("new_attempt", "anna"))
  feed(s:ok("start_run", "anna"))
  feed(s:ok("status", "anna", { has_balls = true }))
  feed(s:ok("catch", "anna", { uid = "b1", species_name = "Chelast", area = H.AREA2 }))
  feed(s:ok("faint", "anna", { uid = "b1", level = 9 }))
  T.eq(#ledger.deathlog, 2)
  T.eq(ledger.deathlog[1].attempt, 1)
  T.eq(ledger.deathlog[2].attempt, 2)
  local text = X.deathlog_all(L.view(ledger, { "anna" }))
  local first = text:find("Versuch 2  Chelast")
  local second = text:find("Versuch 1  Plinfa")
  T.ok(first and second and first < second, text)
  T.ok(text:find("Plinfa %(Anna%) Lv%.6 in Route 201 gegen Rivale – gefallen"), text)
end)

T.test("Todesprotokoll abgeschaltet: keine dauerhaften Einträge", function()
  local s = H.run(1, { settings = { death_log = false } })
  s:ok("catch", "anna", { uid = "a1", area = H.AREA1 })
  local eff = s:ok("faint", "anna", { uid = "a1" })
  T.no(T.find(eff, { type = "death" }))
  T.eq(#s:team("anna").graveyard, 1, "Friedhof bleibt (für die Regeln)")
end)

T.test("Run-Statistik: Endbildschirm und Discord-Meldung beim Run-Ende", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  s:ok("status", "anna", { badges = 2 })
  s:ok("encounter_failed", "ben", { area = H.AREA2 })
  local eff = s:ok("faint", "anna", { uid = "anna-a" })
  T.eq(s.state.phase, "finished")
  local lines = X.summary(s.state)
  T.ok(lines[1]:find("^Versuch 1 – verloren nach"), lines[1])
  T.has({ { t = lines[2] } }, { t = "Orden: Anna 2, Ben 0" })
  T.has({ { t = lines[3] } }, { t = "Tode: Anna 1, Ben 0 (+1 mitgerissen)" })
  T.has({ { t = lines[4] } }, { t = "Gruppen: 1 (0 lebend, 1 tot)" })
  T.has({ { t = lines[5] } }, { t = "Gebiete: 2 betreten, 1 verbraucht" })
  local n = 0
  for _, e in ipairs(eff) do
    if e.type == "discord" and e.kind == "run_end" then
      n = n + 1
      T.ok(e.text:find("Run beendet: verloren"))
      T.ok(e.text:find("Tode: Anna 1"))
    end
  end
  T.eq(n, 1, "bei einem Team genau eine Run-Ende-Meldung")
end)

T.test("Run-Statistik Wettkampf: Plätze und Team-Meldungen", function()
  local s = H.run(2, { teams = { { "anna" }, { "ben" } }, settings = { goal = { kind = "orden", value = 1 } } })
  H.catch_all(s, H.AREA1, "a")
  local e1 = s:ok("status", "ben", { badges = 1 })
  T.has(e1, { type = "discord", kind = "run_end" })
  local e2 = s:ok("faint", "anna", { uid = "anna-a" })
  local n = 0
  for _, e in ipairs(e2) do if e.type == "discord" and e.kind == "run_end" then n = n + 1 end end
  T.eq(n, 2, "Ausscheiden + Run-Ende")
  local lines = X.summary(s.state)
  T.ok(lines[2]:find("^Platz 1: Team 2"), lines[2])
  T.ok(lines[3]:find("^Platz 2: Team 1"), lines[3])
end)

T.test("Zeitleiste: Ereignisse je Spieler, SVG mit Markierungen, Offline-Balken und Legende", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("status", "anna", { badges = 1 })
  s:ok("offline", "ben")
  s:ok("faint", "anna", { uid = "anna-a" })
  s:ok("online", "ben")
  s:ok("encounter_failed", "anna", { area = H.AREA3 })
  local kinds = {}
  for _, e in ipairs(s.state.timeline) do kinds[#kinds + 1] = e.p .. ":" .. e.k end
  T.eq(kinds, { "anna:fang", "ben:fang", "anna:fang", "ben:fang", "anna:orden", "ben:offline", "anna:tot",
    "ben:mitgerissen", "ben:online", "anna:verbraucht" })
  local svg = X.timeline_svg(s.state, s.t + 1000)
  T.ok(svg:find("^<svg"))
  T.ok(svg:find("</svg>\n$"))
  local count = function(pat) local n = 0 for _ in svg:gmatch(pat) do n = n + 1 end return n end
  T.eq(count("<circle"), 4, "vier Fänge")
  T.ok(svg:find("Zeitleiste Versuch 1"))
  T.ok(svg:find(">Anna<") and svg:find(">Ben<"))
  T.ok(svg:find("<title>offline</title>"))
  T.ok(svg:find("Legende") == nil and svg:find(">Gebiet verbraucht<"))
end)

T.test("Zeitleiste: Sonderzeichen werden für XML maskiert, neuer Versuch beginnt leer", function()
  local s = H.run(1)
  s:ok("catch", "anna", { uid = "x", nickname = "<Tom&Co>", area = H.AREA1 })
  local svg = X.timeline_svg(s.state, s.t)
  T.ok(svg:find("&lt;Tom&amp;Co&gt;"), "maskiert")
  T.no(svg:find("<Tom&Co>"))
  s:ok("faint", "anna", { uid = "x" })
  s:ok("new_attempt", "anna")
  s:ok("start_run", "anna")
  T.eq(#s.state.timeline, 0)
end)
