local T = require("lib.t")
local H = require("core.helpers")
local E = require("core.engine")

T.test("Lobby: bis zu 4 Spieler, der fünfte wird abgelehnt", function()
  local s = H.run(4, { start = false })
  local eff = s:ev("join", "erik")
  T.has(eff, { type = "error" })
  T.eq(#s.state.order, 4)
end)

T.test("Lobby: erneuter Beitritt ist idempotent", function()
  local s = H.run(2, { start = false })
  s:ok("join", "anna", { name = "Anna B." })
  T.eq(#s.state.order, 2)
  T.eq(s:p("anna").name, "Anna B.")
end)

T.test("Lobby: Beitritt während des Runs abgelehnt, Wiedereinstieg erlaubt", function()
  local s = H.run(2)
  T.has(s:ev("join", "cem"), { type = "error" })
  s:ok("join", "anna")
end)

T.test("Lobby: Vorlage und Einzeländerung", function()
  local s = H.run(2, { start = false })
  s:ok("set_settings", "anna", { preset = "hardcore" })
  T.eq(s.state.settings.preset, "hardcore")
  T.eq(s.state.settings.rare_candies, false)
  T.eq(s.state.settings.grace, false)
  T.eq(s.state.settings.battle_items.mode, "verboten")
  s:ok("set_settings", "ben", { changes = { grace = true } })
  T.eq(s.state.settings.grace, true)
  s:ok("set_settings", "ben", { preset = "locker" })
  T.eq(s.state.settings.level_cap, false)
  T.eq(s.state.settings.follow_mode, false)
end)

T.test("Lobby: ungültige Einstellungen werden abgelehnt", function()
  local s = H.run(1, { start = false })
  T.has(s:ev("set_settings", "anna", { changes = { gibtsnicht = true } }), { type = "error" })
  T.has(s:ev("set_settings", "anna", { changes = { grace = "ja" } }), { type = "error" })
  T.has(s:ev("set_settings", "anna", { changes = { battle_items = { mode = "manchmal" } } }), { type = "error" })
  T.has(s:ev("set_settings", "anna", { preset = "extrem" }), { type = "error" })
  T.eq(s.state.settings.grace, true)
end)

T.test("Lobby: Einstellungen während des Runs nur per Abstimmung", function()
  local s = H.run(2)
  T.has(s:ev("set_settings", "anna", { changes = { grace = false } }), { type = "error" })
end)

T.test("Run-Start: ein Team mit allen Spielern, Versuchszähler", function()
  local s = H.run(3, { start = false })
  local eff = s:ok("start_run", "anna")
  T.eq(s.state.phase, "running")
  T.eq(s.state.attempt, 1)
  T.eq(#s.state.team_order, 1)
  T.eq(s.state.teams.t1.members, { "anna", "ben", "cem" })
  T.eq(H.count(eff, { type = "stat", key = "attempts" }), 3)
  T.has(eff, { type = "discord", kind = "run_start" })
  T.has(s:ev("start_run", "anna"), { type = "error" })
end)

T.test("Teams: Einteilung prüfen, ungleiche Größen mit Hinweis", function()
  local s = H.run(4, { start = false })
  T.has(s:ev("set_teams", "anna", { teams = { { "anna", "ben" }, { "cem" } } }), { type = "error" })
  T.has(s:ev("set_teams", "anna", { teams = { { "anna", "ben" }, { "ben", "cem", "dana" } } }), { type = "error" })
  T.has(s:ev("set_teams", "anna", { teams = { { "anna", "ben" }, { "cem", "xyz" } } }), { type = "error" })
  local eff = s:ok("set_teams", "anna", { teams = { { "anna", "ben" }, { "cem" }, { "dana" } } })
  T.has(eff, { type = "notify", level = "warn" })
  eff = s:ok("set_teams", "anna", { teams = { { "anna", "ben" }, { "cem", "dana" } } })
  T.no(T.find(eff, { type = "notify", level = "warn" }))
  s:ok("start_run", "anna")
  T.eq(#s.state.team_order, 2)
  T.eq(s:p("cem").team, "t2")
end)

T.test("Neuer Versuch erst nach Run-Ende; Verlauf bleibt erhalten", function()
  local s = H.run(1)
  T.has(s:ev("new_attempt", "anna"), { type = "error" })
  H.catch_all(s, H.AREA1, "a")
  s:ok("faint", "anna", { uid = "anna-a" })
  T.eq(s.state.phase, "finished")
  T.eq(s.state.result, "verloren")
  T.eq(#s.state.history, 1)
  s:ok("new_attempt", "anna")
  T.eq(s.state.phase, "lobby")
  T.eq(s:p("anna").deaths, 0)
  s:ok("start_run", "anna")
  T.eq(s.state.attempt, 2)
  T.eq(#s.state.history, 1)
  T.eq(s.state.counters.group, 0)
end)

T.test("Fehlerhafte Ereignisse verändern den Zustand nicht", function()
  local s = H.run(2)
  local json = require("lib.json")
  local before = json.encode(s.state)
  T.has(s:ev("catch", "anna", { species = 1 }), { type = "error" })
  T.has(s:ev("gibtsnicht", "anna"), { type = "error" })
  T.has(s:ev("faint", "zoe", { uid = "x" }), { type = "error" })
  T.eq(json.encode(s.state), before)
end)

T.test("Zustand ist reines JSON und übersteht die Rundreise", function()
  local json = require("lib.json")
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  local text = json.encode(s.state)
  local back = json.decode(text)
  T.eq(json.encode(back), text)
  -- Weiterarbeiten auf dem dekodierten Zustand
  local eff = E.apply(back, { type = "faint", player = "anna", uid = "anna-a", t = 99999 })
  T.has(eff, { type = "kill", player = "ben", uid = "ben-a" })
end)
