-- Tipprunde vor Arenen.
local T = require("lib.t")
local H = require("core.helpers")
local L = require("core.ledger")

local function setup()
  local s = H.run(3)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  H.catch_all(s, H.AREA3, "c")
  return s
end

T.test("Tipprunde: öffnen, tippen, beim Orden auflösen, Punkte für richtige Tipps", function()
  local s = setup()
  local ledger = L.new()
  local eff = s:ok("tip_open", "anna")
  T.has(eff, { type = "discord", kind = "tip" })
  T.has(s:ev("tip_open", "ben", { target = "anna" }), { type = "error" }, "nur eine Runde je Spieler")
  s:ok("tip", "ben", { round = "r1", option = "ohne_tod" })
  s:ok("tip", "cem", { round = "r1", option = "ein_tod" })
  s:ok("tip", "anna", { target = "anna", option = "ein_tod" })
  T.has(s:ev("tip", "cem", { round = "r1", option = "quatsch" }), { type = "error" })
  s:ok("faint", "anna", { uid = "anna-a" })
  T.has(s:ev("tip", "ben", { round = "r1", option = "mehr" }), { type = "error" }, "nach erstem Tod geschlossen")
  eff = s:ok("status", "anna", { badges = 1 })
  L.apply(ledger, eff, {}, 1)
  local r = s.state.tips.r1
  T.eq(r.status, "aufgeloest")
  T.eq(r.result, "ein_tod")
  T.eq(ledger.players.cem.tip_points, 1)
  T.eq(ledger.players.anna.tip_points, 1)
  T.eq(ledger.players.ben, nil)
  local n = nil
  for _, e in ipairs(eff) do if e.type == "notify" and e.text:find("Tipprunde Anna") then n = e end end
  T.ok(n and n.text:find("1 Tod%. Richtig getippt: Anna, Cem"), n and n.text)
end)

T.test("Tipprunde: im Kampf geschlossen; Ausscheiden löst mit „2+“ auf", function()
  local s = H.run(2, { teams = { { "anna" }, { "ben" } } })
  H.catch_all(s, H.AREA1, "a")
  s:ok("tip_open", "ben", { target = "anna" })
  s:ok("tip", "ben", { round = "r1", option = "mehr" })
  s:ok("status", "anna", { in_battle = true })
  T.has(s:ev("tip", "anna", { round = "r1", option = "ohne_tod" }), { type = "error" })
  s:ok("faint", "anna", { uid = "anna-a" })
  T.eq(s.state.tips.r1.result, "mehr")
  T.eq(s.state.teams.t1.status, "verloren")
  T.has(s:ev("tip_open", "ben", { target = "anna" }), { type = "error" }, "ausgeschieden")
end)

T.test("Neuer Versuch leert die Tipprunden", function()
  local s = H.run(1)
  H.catch_all(s, H.AREA1, "a")
  s:ok("tip_open", "anna")
  s:ok("faint", "anna", { uid = "anna-a" })
  s:ok("new_attempt", "anna")
  s:ok("start_run", "anna")
  T.eq(next(s.state.tips), nil)
end)
