local T = require("lib.t")
local RomFS = require("rando.romfs")
local F = require("rando.romfake")

T.test("NDS-Dateisystem: Pfade und Dateien", function()
  local narc = F.narc({ "eins", "zwei!" })
  local rom = RomFS.new(F.reader(F.rom("pl_enc_data.narc", narc, "CPUD")))
  T.eq(rom.game_code, "CPUD")
  local paths = rom:list()
  T.eq(paths["a.bin"], 0)
  T.eq(paths["fielddata/encountdata/pl_enc_data.narc"], 1)
  T.eq(rom:file("a.bin"), "HALLO")
  T.eq(rom:file("fielddata/encountdata/pl_enc_data.narc"), narc)
  local none, err = rom:file("gibt/es/nicht")
  T.eq(none, nil)
  T.ok(err:find("nicht im ROM"))
end)

T.test("NARC zerlegen", function()
  local files = RomFS.narc(F.narc({ "eins", "", "drei" }))
  T.eq(files, { "eins", "", "drei" })
  T.eq(RomFS.narc("kaputt"), nil)
end)
