local T = require("lib.t")
local H = require("core.helpers")
local Enforce = require("app.enforce")

local function snap(party, battle)
  return { t = 0, party = party, battle = battle }
end

T.test("Ohne laufenden Run: nichts tun", function()
  local plan = Enforce.plan(nil, "anna", snap({}))
  T.no(plan.lock)
  T.eq(#plan.hp_zero, 0)
end)

T.test("Tote Monster auf 0 KP halten und nach dem Kampf sperren", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("faint", "anna", { uid = "anna-a" })
  local party = { { uid = "ben-a", hp = 12 }, { uid = "ben-b", hp = 30 } }
  -- im Kampf: KP auf 0, aber keine Sperre
  local plan = Enforce.plan(s.state, "ben", snap(party, { wild = true }))
  T.eq(plan.hp_zero, { "ben-a" })
  T.no(plan.lock)
  -- nach dem Kampf: Sperre mit Begründung
  plan = Enforce.plan(s.state, "ben", snap(party))
  T.ok(plan.lock)
  T.eq(plan.lock_mode, "menu")
  T.ok(plan.reasons[1]:find("Tot, muss in die Box"))
  -- bereits auf 0: kein erneutes Schreiben
  plan = Enforce.plan(s.state, "ben", snap({ { uid = "ben-a", hp = 0 }, { uid = "ben-b", hp = 30 } }))
  T.eq(#plan.hp_zero, 0)
  -- in der Box: keine Sperre mehr (sofern Teams gleich)
  s:ok("party", "anna", { mons = { "anna-b" } })
  plan = Enforce.plan(s.state, "ben", snap({ { uid = "ben-b", hp = 30 } }))
  T.no(plan.lock)
end)

T.test("Totes Monster aus der Box ins Team genommen: Sperre sofort", function()
  local s = H.run(1)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("faint", "anna", { uid = "anna-a" })
  local plan = Enforce.plan(s.state, "anna", snap({ { uid = "anna-b", hp = 5 }, { uid = "anna-a", hp = 0 } }))
  T.ok(plan.lock)
end)

T.test("Team-Ungleichheit sperrt mit Angabe, was fehlt und was zu viel ist", function()
  local s = H.run(2)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("party", "anna", { mons = { "anna-a" } })
  local plan = Enforce.plan(s.state, "ben", snap({ { uid = "ben-a", hp = 5 }, { uid = "ben-b", hp = 5 } }))
  T.ok(plan.lock)
  T.ok(plan.reasons[1]:find("Zu viel im Team"))
  plan = Enforce.plan(s.state, "anna", snap({ { uid = "anna-a", hp = 5 } }))
  T.no(plan.lock, "ben hat noch kein Team gemeldet")
end)

T.test("Abwesenheitsliste sperrt vollständig bis zur Bestätigung", function()
  local s = H.run(2)
  local plan = Enforce.plan(s.state, "anna", snap({}), { absence_pending = true })
  T.ok(plan.lock)
  T.eq(plan.lock_mode, "voll")
  local mask = Enforce.joypad_mask(plan, true)
  T.eq(mask.start, false)
  T.eq(mask.A, false)
end)

T.test("Menü-Sperre: nur Start/X, im Menü auch Steuerkreuz und A/B", function()
  local plan = { lock = true, lock_mode = "menu" }
  local mask = Enforce.joypad_mask(plan, false)
  T.eq(mask.start, nil)
  T.eq(mask.X, nil)
  T.eq(mask.up, false)
  T.eq(mask.A, false)
  mask = Enforce.joypad_mask(plan, true)
  T.eq(mask.up, nil)
  T.eq(mask.A, nil)
  T.eq(mask.L, false)
  T.eq(Enforce.joypad_mask({ lock = false }), nil)
end)

T.test("Kurzzeitige Freigabe für den Weg zum PC", function()
  local s = H.run(1)
  H.catch_all(s, H.AREA1, "a")
  H.catch_all(s, H.AREA2, "b")
  s:ok("faint", "anna", { uid = "anna-a" })
  local party = { { uid = "anna-a", hp = 0 }, { uid = "anna-b", hp = 9 } }
  local plan = Enforce.plan(s.state, "anna", snap(party), { override_until = 5000, now = 1000 })
  T.no(plan.lock)
  plan = Enforce.plan(s.state, "anna", snap(party), { override_until = 5000, now = 6000 })
  T.ok(plan.lock)
end)
